#!/bin/sh

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done

public_remote_url="https://github.com/PrincetonUniversity/athena-public-version.git"

public_local_branch="public"
private_local_branch="master"


remote="$1"
# remote url
url="$2"
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
echo branch: $branch
echo command line: $*
echo remote: $remote
echo url: $url

# Check that we are not pushing private results to
# the public branch
if ! [ $branch = $public_local_branch ] && [ $url = $public_remote_url ]
then
    echo You are pushing the \(private\) $branch branch to the public repo.
    echo This is not allowed.
    exit 1
fi
exit 0
